language: node_js
node_js:
  - "12"
  - "11"
  - "10"
  - "8"
cache:
  npm: true
  directories:
    - node_modules
install:
  - npm install
  - npm install codecov -g
script:
  - npm test
after_success:
- codecov -f coverage/coverage-final.json
